// const QUESTION_TEMPLATES = [
//   "{assetSymbol} will move {directionWord} in the next {duration} minutes?",
//   "Do you think {assetSymbol} will reach ${target} within {duration} minutes?",
//   "Is {assetSymbol} going to be above ${target} at market close?",
//   "Can {assetSymbol} drop below ${target} in {duration} minutes?",
//   "Do you expect {assetSymbol} to trade above ${target} by {endTime}?",
//   "Will the price of {assetSymbol} exceed ${target} before expiry?",
//   "Do you expect {assetSymbol} price to drop below ${target} this week?",
//   "Will {assetSymbol} end {duration} above ${target}?",
//   "{assetSymbol} crossing ${target} in the next {duration} minutes?",
//   "Do you think {assetSymbol} will close above ${target} by end of day?",
//   "{assetSymbol} volatility exceeding {percent}% this week?",
//   "Do you expect {assetSymbol} price to be {directionWord} tomorrow?",
//   "Will {assetSymbol} break ${target} today?",
//   "Do you think {assetSymbol} will stay above ${target} this week?",
//   "Is {assetSymbol} likely to drop below ${target} in {duration} minutes?",
//   "{assetSymbol} moving {directionWord} in the next {duration} hours?",
//   "Could {assetSymbol} surpass ${target} by {endTime}?",
//   "Will {assetSymbol} price exceed ${target} during {duration}?",
//   "Can {assetSymbol} reach ${target} before {endTime}?",
//   "Is {assetSymbol} going to hit a new low before {endTime}?",
//   "{assetSymbol} closing above ${target} by {endTime}?",
//   "Do you expect {assetSymbol} volatility to stay above {percent}%",
//   "Will {assetSymbol} trade below ${target} at market close?",
//   "{assetSymbol} hitting ${target} within {duration} hours?",
//   "Will {assetSymbol} recover above ${target} after a dip?",
//   "Can {assetSymbol} exceed ${target} during {duration}?",
//   "Do you expect {assetSymbol} to stay {directionWord} tomorrow?",
//   "Will {assetSymbol} price fluctuate more than {percent}% this week?",
//   "Do you expect {assetSymbol} to hit ${target} before {endTime}?",
//   "{assetSymbol} moving {directionWord} in the next {duration} hours?",
//   "Is {assetSymbol} likely to reach ${target} within {duration} minutes?",
//   "Do you expect {assetSymbol} to trade {directionWord} today?",
//   "Will {assetSymbol} price stay above ${target} until market close?",
//   "{assetSymbol} crossing ${target} in the next {duration} hours?",
//   "Can {assetSymbol} reach ${target} after a small dip?",
//   "Will {assetSymbol} close {directionWord} compared to the open?",
//   "Is {assetSymbol} likely to hit ${target} before the end of day?",
//   "Do you think {assetSymbol} will stay {directionWord} for the next {duration} hours?",
//   "{assetSymbol} price fluctuating more than {percent}% in the next {duration} minutes?",
//   "Will {assetSymbol} recover to ${target} after recent movement?",
//   "Can {assetSymbol} break ${target} during the next {duration} minutes?",
//   "Do you expect {assetSymbol} price to remain {directionWord} in the next {duration} hours?",
//   "{assetSymbol} moving {directionWord} and hitting ${target} soon?",
//   "Will {assetSymbol} surpass ${target} before the next interval?",
//   "Do you think {assetSymbol} will maintain its {directionWord} trend?",
//   "Is {assetSymbol} likely to trade above ${target} by {endTime}?",
//   "Will {assetSymbol} price stay below ${target} for {duration} minutes?",
//   "Can {assetSymbol} reach ${target} during the next {duration} hours?",
//   "Do you expect {assetSymbol} to move {directionWord} beyond ${target}?",
//   "Will {assetSymbol} close above ${target} in the next {duration} minutes?",
//   "Is {assetSymbol} likely to hit ${target} within the current session?",
//   "Can {assetSymbol} stay {directionWord} over the next {duration} minutes?",
//   "{assetSymbol} breaking ${target} before the next market check?"
// ];

// module.exports = { QUESTION_TEMPLATES };

const QUESTION_TEMPLATES = [
  "Will {assetSymbol} be above ${target} in the next {duration} ?",
  // "Will the next {assetSymbol} candle close {directionWord} in {duration} ?",
  // "Can {assetSymbol} break above ${target} within {duration} ?",
  // "Will {assetSymbol} stay {directionWord} for the next {duration} ?",
  // "Is {assetSymbol} likely to drop below ${target} in {duration} ?"
];

module.exports = { QUESTION_TEMPLATES };