const QUESTION_TEMPLATES = [
  "{asset} will move {directionWord} in the next {duration} minutes?",
  "Do you think {asset} will reach ${target} within {duration} minutes?",
  "Is {asset} going to be above ${target} at market close?",
  "Can {asset} drop below ${target} in {duration} minutes?",
  "Do you expect {asset} to trade above ${target} by {endTime}?",
  "Will the price of {asset} exceed ${target} before expiry?",
  "Do you expect {asset} price to drop below ${target} this week?",
  "Will {asset} end {duration} above ${target}?",
  "{asset} crossing ${target} in the next {duration} minutes?",
  "Do you think {asset} will close above ${target} by end of day?",
  "{asset} volatility exceeding {percent}% this week?",
  "Do you expect {asset} price to be {directionWord} tomorrow?",
  "Will {asset} break ${target} today?",
  "Do you think {asset} will stay above ${target} this week?",
  "Is {asset} likely to drop below ${target} in {duration} minutes?",
  "{asset} moving {directionWord} in the next {duration} hours?",
  "Could {asset} surpass ${target} by {endTime}?",
  "Will {asset} price exceed ${target} during {duration}?",
  "Can {asset} reach ${target} before {endTime}?",
  "Is {asset} going to hit a new low before {endTime}?",
  "{asset} closing above ${target} by {endTime}?",
  "Do you expect {asset} volatility to stay above {percent}%",
  "Will {asset} trade below ${target} at market close?",
  "{asset} hitting ${target} within {duration} hours?",
  "Will {asset} recover above ${target} after a dip?",
  "Can {asset} exceed ${target} during {duration}?",
  "Do you expect {asset} to stay {directionWord} tomorrow?",
  "Will {asset} price fluctuate more than {percent}% this week?",
  "Do you expect {asset} to hit ${target} before {endTime}?",
  "{asset} moving {directionWord} in the next {duration} hours?",
  "Is {asset} likely to reach ${target} within {duration} minutes?",
  "Do you expect {asset} to trade {directionWord} today?",
  "Will {asset} price stay above ${target} until market close?",
  "{asset} crossing ${target} in the next {duration} hours?",
  "Can {asset} reach ${target} after a small dip?",
  "Will {asset} close {directionWord} compared to the open?",
  "Is {asset} likely to hit ${target} before the end of day?",
  "Do you think {asset} will stay {directionWord} for the next {duration} hours?",
  "{asset} price fluctuating more than {percent}% in the next {duration} minutes?",
  "Will {asset} recover to ${target} after recent movement?",
  "Can {asset} break ${target} during the next {duration} minutes?",
  "Do you expect {asset} price to remain {directionWord} in the next {duration} hours?",
  "{asset} moving {directionWord} and hitting ${target} soon?",
  "Will {asset} surpass ${target} before the next interval?",
  "Do you think {asset} will maintain its {directionWord} trend?",
  "Is {asset} likely to trade above ${target} by {endTime}?",
  "Will {asset} price stay below ${target} for {duration} minutes?",
  "Can {asset} reach ${target} during the next {duration} hours?",
  "Do you expect {asset} to move {directionWord} beyond ${target}?",
  "Will {asset} close above ${target} in the next {duration} minutes?",
  "Is {asset} likely to hit ${target} within the current session?",
  "Can {asset} stay {directionWord} over the next {duration} minutes?",
  "{asset} breaking ${target} before the next market check?"
];

module.exports = { QUESTION_TEMPLATES };